# TCL File Generated by Component Editor 12.1sp1
# Mon Mar 13 14:20:47 MDT 2017
# DO NOT MODIFY


# 
# pwm_generator "pwm_generator" v1.0
# null 2017.03.13.14:20:47
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module pwm_generator
# 
set_module_property NAME pwm_generator
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME pwm_generator
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pwm_generator
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file pwm_generator.vhd VHDL PATH vhd/pwm_generator.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock_sink
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true

add_interface_port clock_sink clock clk Input 1


# 
# connection point pwm_out
# 
add_interface pwm_out conduit end
set_interface_property pwm_out associatedClock clock_sink
set_interface_property pwm_out associatedReset reset
set_interface_property pwm_out ENABLED true

add_interface_port pwm_out pwm_out export Output 1


# 
# connection point avalon_slave_period
# 
add_interface avalon_slave_period avalon end
set_interface_property avalon_slave_period addressUnits WORDS
set_interface_property avalon_slave_period associatedClock clock_sink
set_interface_property avalon_slave_period associatedReset reset
set_interface_property avalon_slave_period bitsPerSymbol 8
set_interface_property avalon_slave_period burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_period burstcountUnits WORDS
set_interface_property avalon_slave_period explicitAddressSpan 0
set_interface_property avalon_slave_period holdTime 0
set_interface_property avalon_slave_period linewrapBursts false
set_interface_property avalon_slave_period maximumPendingReadTransactions 0
set_interface_property avalon_slave_period readLatency 0
set_interface_property avalon_slave_period readWaitTime 1
set_interface_property avalon_slave_period setupTime 0
set_interface_property avalon_slave_period timingUnits Cycles
set_interface_property avalon_slave_period writeWaitStates 1
set_interface_property avalon_slave_period writeWaitTime 1
set_interface_property avalon_slave_period ENABLED true

add_interface_port avalon_slave_period write_en_period write Input 1
add_interface_port avalon_slave_period period writedata Input 32
set_interface_assignment avalon_slave_period embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_period embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_period embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_period embeddedsw.configuration.isPrintableDevice 0


# 
# connection point avalon_slave_duty
# 
add_interface avalon_slave_duty avalon end
set_interface_property avalon_slave_duty addressUnits WORDS
set_interface_property avalon_slave_duty associatedClock clock_sink
set_interface_property avalon_slave_duty associatedReset reset
set_interface_property avalon_slave_duty bitsPerSymbol 8
set_interface_property avalon_slave_duty burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_duty burstcountUnits WORDS
set_interface_property avalon_slave_duty explicitAddressSpan 0
set_interface_property avalon_slave_duty holdTime 0
set_interface_property avalon_slave_duty linewrapBursts false
set_interface_property avalon_slave_duty maximumPendingReadTransactions 0
set_interface_property avalon_slave_duty readLatency 0
set_interface_property avalon_slave_duty readWaitTime 1
set_interface_property avalon_slave_duty setupTime 0
set_interface_property avalon_slave_duty timingUnits Cycles
set_interface_property avalon_slave_duty writeWaitStates 1
set_interface_property avalon_slave_duty writeWaitTime 1
set_interface_property avalon_slave_duty ENABLED true

add_interface_port avalon_slave_duty duty_count writedata Input 32
add_interface_port avalon_slave_duty write_en_duty write Input 1
set_interface_assignment avalon_slave_duty embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_duty embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_duty embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_duty embeddedsw.configuration.isPrintableDevice 0

